import { test } from "node:test";
import assert from "node:assert/strict";
import { componentAddress, toHex } from "../src/index.ts";

test("addresses are deterministic and distinct per (world, entity, component)", () => {
  const a = componentAddress(1n, 1n, 1);
  assert.deepEqual(a, componentAddress(1n, 1n, 1));
  assert.notDeepEqual(a, componentAddress(2n, 1n, 1));
  assert.notDeepEqual(a, componentAddress(1n, 2n, 1));
  assert.notDeepEqual(a, componentAddress(1n, 1n, 2));
  assert.equal(toHex(a).length, 64);
});

test("matches the Rust core byte-for-byte (cross-vectors)", () => {
  // Generated by `cargo run --example vectors` in engine-core.
  assert.equal(
    toHex(componentAddress(42n, 3n, 1)),
    "02909d9070dd2df9a51732211c1aec168cbb13ab8f50d547afd9a1b418daebe7",
  );
  assert.equal(
    toHex(componentAddress(1n, 1n, 0)),
    "eab4eb3cf4099ec1cd7f5bf8baab4771a41e67905fe5a5ae87e9d64b26874f5e",
  );
});
