import { test } from "node:test";
import assert from "node:assert/strict";
import { fnv1a, Hasher, utf8 } from "../src/index.ts";

test("FNV-1a 64 known vectors", () => {
  assert.equal(fnv1a(utf8("")), 0xcbf29ce484222325n);
  assert.equal(fnv1a(utf8("a")), 0xaf63dc4c8601ec8cn);
  assert.equal(fnv1a(utf8("foobar")), 0x85944171f73967e8n);
});

test("matches the Rust core (cross-vector)", () => {
  // Generated by `cargo run --example vectors` in engine-core.
  assert.equal(fnv1a(utf8("loom")), 0xcdecefad70d5909cn);
});

test("streaming equals one-shot", () => {
  const streamed = new Hasher().write(utf8("foo")).write(utf8("bar")).finish();
  assert.equal(streamed, fnv1a(utf8("foobar")));
});
