// Codegen - produce a typed TypeScript client from an on-chain schema.
// Emits an interface and id constant per Component so field access is
// type-checked rather than stringly-typed.

import type { FieldType, SchemaRegistry } from "./schema.ts";

function tsType(ty: FieldType): string {
  if (typeof ty === "object") return "Uint8Array";
  switch (ty) {
    case "u8":
    case "u16":
    case "u32":
      return "number";
    case "u64":
    case "i64":
    case "entity":
      return "bigint";
    case "bool":
      return "boolean";
    case "pubkey":
      return "Uint8Array";
  }
}

/** Generate a `.ts` module of typed Component interfaces from a registry. */
export function generateClient(registry: SchemaRegistry): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @loom/sdk codegen from the on-chain schema. Do not edit.");
  lines.push("");

  for (const schema of registry.iter()) {
    lines.push(`export interface ${schema.name} {`);
    for (const f of schema.fields) {
      lines.push(`  ${f.name}: ${tsType(f.ty)};`);
    }
    lines.push("}");
    lines.push("");
  }

  lines.push("export const Components = {");
  for (const schema of registry.iter()) {
    lines.push(`  ${schema.name}: ${schema.id},`);
  }
  lines.push("} as const;");
  lines.push("");

  const names = registry.iter().map((s) => `"${s.name}"`);
  lines.push(`export type ComponentName = ${names.length ? names.join(" | ") : "never"};`);
  lines.push("");

  return lines.join("\n");
}
